import type { Metadata } from "next";
import { Montserrat, Roboto } from "next/font/google";
import "./globals.css"

const montserrat = Montserrat({
	weight: ["400", "700"], 
	subsets: ["latin"], 
	variable: "--font-montserrat", 
})

const roboto = Roboto({
	weight: ["400", "700"],
	subsets: ["latin"],
	variable: "--font-roboto",
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
		<html lang="en">
			<head>
				<script async src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.6.1/socket.io.min.js"></script>
				<script async src="https://unpkg.com/chessboardjs/dist/chessboard-1.0.0.min.js"></script>
				<script async src="https://cdnjs.cloudflare.com/ajax/libs/chess.js/0.12.0/chess.min.js"></script>
			</head>
			<body className={`${montserrat.variable} ${roboto.variable}`}>
				{children}
			</body>
		</html>
	)
}
